<STYLE type="text/css">
body { 
        scrollbar-3dlight-color:#666666;
        scrollbar-arrow-color:#000000;
        scrollbar-darkshadow-color:#000000;
        scrollbar-face-color:#999999;
        scrollbar-highlight-color:#666666;
        scrollbar-track-color:#666666; 
        scrollbar-shadow-color:#333333;
}

	a.text:link {color: #000000; font-family:tahoma; font-size:9pt;}
	a.text:visited {color: #000000; font-family:tahoma; font-size:9pt;} 
	a.text:hover {color: #000000; font-family:tahoma; font-size:9pt;} 
	a.text:active {color: #000000; font-family:tahoma; font-size:9pt;} 
	a.text2:link {color: #FFFFFF; font-family:tahoma; font-size:9pt;} 
	a.text2:visited {color: #FFFFFF; font-family:tahoma; font-size:9pt;}
	a.text2:hover {color: #FFFFFF; font-family:tahoma; font-size:9pt;}
	a.text2:active {color: #FFFFFF; font-family:tahoma; font-size:9pt;}
	.zarko {color: #000000; font-family:tahoma; font-size:8pt;}
	.display {color: #000000; font-family:tahoma; font-size:9pt;}
	.display2 {color: #FFFFFF; font-family:tahoma; font-size:9pt;}
	.cart1 {color: #FFFFFF; font-family:tahoma; font-size:8pt;} 
	a.cart2:link {color: #000000; font-family:tahoma; font-size:8pt;}
	a.cart2:visited {color: #000000; font-family:tahoma; font-size:8pt;} 
	a.cart2:hover {color: #000000; font-family:tahoma; font-size:8pt;} 
	a.cart2:active {color: #000000; font-family:tahoma; font-size:8pt;} 
	a.cart3:link {color: #FFFFFF; font-family:tahoma; font-size:8pt;}
	a.cart3:visited {color: #FFFFFF; font-family:tahoma; font-size:8pt;} 
	a.cart3:hover {color: #FFFFFF; font-family:tahoma; font-size:8pt;} 
	a.cart3:active {color: #FFFFFF; font-family:tahoma; font-size:8pt;}
	.error {color: #000000; font-family:tahoma; font-size:10pt;}

</STYLE>