<?php

print "
	<option value=\"MEETING\">MEETING</option> 
	<option value=\"ADMINISTRATION\">ADMINISTRATION</option> 
	<option value=\"RESEARCH\">RESEARCH</option> 
	<option value=\"DATA COLLECTION\">DATA COLLECTION</option> 
	<option value=\"SOFTWARE DEV\">SOFTWARE DEV</option> 
	<option value=\"INTERNAL DEV\">INTERNAL DEV</option> 
	<option value=\"MAINTENANCE\">MAINTENANCE</option> 
	<option value=\"PRODUCTION\">PRODUCTION</option> 
";

?>